FROM node:14.15.3-buster-slim

RUN apt update && \
    apt install -y \
      vim curl wget git

COPY ./node_modules/@dqbd/tiktoken /node_modules/@dqbd/tiktoken
COPY ./packages/cli/pkg/linux/salto /usr/local/bin/salto
